RFCxxxx: Support overloaded objects in join(), substr() builtins
Perl/RFCs pull request #9
Opened 2021-11-23 07:14 UTC by book

Pre-RFC discussion: https://www.nntp.perl.org/group/perl.perl5.porters/2021/11/msg261831.html

2021-11-23 18:31 UTC, ilmari requested changes
:+1: for the concept!

2021-11-23 18:31 UTC, ilmari commented on rfcs/rfcXXXX.md
> +`[overload::substr](https://metacpan.org/pod/overload::substr)`) is a
```suggestion
[`overload::substr`](https://metacpan.org/pod/overload::substr) is a
```

2021-11-23 18:31 UTC, ilmari commented on rfcs/rfcXXXX.md
> +version-conditional logic to work with different versions of Perl.
Surely they don't _need_ to, unless they enable the feature flag (which would presumably be lexical)?

However, they can (conditionally) take advantage of the built-in `join` respecting overloading, and delegate to that when available.

2021-11-23 18:31 UTC, ilmari commented on rfcs/rfcXXXX.md
> +    ```perl
Use either indentation or code fences for verbatim blocks, not both. Code fences are better, since they let you specify the language.

2021-12-15 15:56 UTC, leonerd commented
LGTM

By my count the next RFC number would be 0010.

2022-01-21 14:59 UTC, neilb commented
Can you set the number to 0013 please @book ?

2022-01-28 14:38 UTC, leonerd commented on rfcs/rfc0013.md
> +    ID:
This should be 0013

2022-01-28 15:14 UTC, merged